language: node_js

node_js:
  - node
  - 10
  # - 8

install:
  - npm install
  - npm install -g codecov

script:
  - npm run lint
  - npm run test
  - codecov

branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'

# jobs:
#   include:
#     - stage: deploy
#       if: branch == master && !fork
#       node_js: 'node' # pre-installed version
#       script:
#         - npm install -g semantic-release@^15
#         - semantic-release

# jobs:
#   include:
#     - stage: release
#       if: branch = master
#       name: "Releasing"             # names the releasing stage job
#       # node_js: lts/*
#       node_js: 'node' # pre-installed version
#       # Advanced: optionally overwrite your default `script` step to skip the tests
#       # script: skip
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script:
#           - npx semantic-release
