language: node_js

node_js:
  - node
  - 10
  # - 8

before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1

install:
  - npm install
  - npm install -g codecov

before_script: greenkeeper-lockfile-update

script:
  - npm run lint
  - npm run test
  - codecov

after_script: greenkeeper-lockfile-upload

after_success:
  - npx semantic-release
  if: branch = master
  name: "Releasing"             # names the releasing stage job

branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
